### ISSUE TITLE
Is there any option to show the actual number in the center?

### ISSUE THREAD

**Issue by happyshows** [timelyportfolio/sunburstR#1]
Like the one below:
http://bl.ocks.org/mkajava/7515402

To me it's much useful to show both percentage & actual number as default.

**Comment by timelyportfolio** [comment]
As of now, not easy, but shouldn't be to hard to add.  Just not sure how much time I'll have to implement.  Thanks for the suggestion.

**Comment by timelyportfolio** [comment]
Feel free to reopen.  Thanks!
