### ISSUE TITLE
plot not generating

### ISSUE THREAD

**Issue by hoshw** [timelyportfolio/sunburstR#11]
I'm having trouble generating a plot with my own data and was wondering if there were any character or path/character length limitations that should be kept in mind.

**Comment by timelyportfolio** [comment]
@hoshw, glad you are trying `sunburstR`.  I would start by reading the notes to http://bl.ocks.org/kerryrodden/7090426.  Let me know if you are still unsure.

**Comment by timelyportfolio** [comment]
Reopen if you are still having trouble
