### ISSUE TITLE
warning when using sunburstOutput with shiny 1.7.4 (latest CRAN)

### ISSUE THREAD

**Issue by ismirsehregal** [timelyportfolio/sunburstR#115]
When using `sunburstOutput` in a shiny app (latest CRAN version) the following warning is thrown after closing the app:

Warning message:

> `bindFillRole()` only works on htmltools::tag() objects (e.g., div(), p(), etc.), not objects of type 'shiny.tag.list'. 

Example (slightly modified version of [this](https://github.com/timelyportfolio/sunburstR/blob/master/inst/examples/example_shiny.R)):

```
library(shiny)
library(sunburstR)

sequences <- read.csv(
  system.file("examples/visit-sequences.csv", package = "sunburstR"),
  header = FALSE,
  stringsAsFactors = FALSE
)

server <- function(input, output, session) {
  output$sunburst <- renderSunburst({
    #invalidateLater(1000, session)
    sequences <-
      sequences[sample(nrow(sequences), 1000, replace = TRUE), ]
    add_shiny(sunburst(sequences))
  })
  
  selection <- reactive({
    input$sunburst_mouseover
  })
  
  output$selection <- renderText(selection())
}

ui <- fluidPage(sidebarLayout(sidebarPanel(),
                              # plot sunburst
                              mainPanel(
                                sunburstOutput("sunburst"),
                                textOutput("selection")
                              )))

shinyApp(ui = ui, server = server)
```

**Comment by hammerPC** [comment]
您好，信件我已收到，将会尽快回复。   王鹏超

**Comment by timelyportfolio** [comment]
@ismirsehregal thanks so much for the report.  I believe we can fix pretty easily by removing the enclosing `tagList`.  I have committed the change and am submitting to CRAN.  Please let me know if you experience any other challenges.

**Comment by ismirsehregal** [comment]
I can confirm the warning is gone after using the dev version. Thanks for your swift investigation @timelyportfolio!
