### ISSUE TITLE
features/ideas from blog comment

### ISSUE THREAD

**Issue by timelyportfolio** [timelyportfolio/sunburstR#2]
@markriseley suggested in [comments to the blog post](http://www.buildingwidgets.com/blog/2015/7/2/week-26-sunburstr#comments-55958c8ce4b0e9796cc1c05f=).  This issue will track progress on his good ideas.

```
Thanks it's great to see this!

A couple of suggestions for making this really sharp for all-purpose use (which push beyond the original JS I know):

1) Supply an optional legend order argument vector eg c("home", "about"....)
2) Supply your own colour palette, mapped to the legend order if given (eg vector of hex codes)
3) Add a parameter 'centreText' which allows you to supply additional span text eg paste0(percentage, " of visits started with this sequence") inside the circle
4) Optionally (as a default) suppress "root" node from legend and colour scale calculations (as I don't think it would ever have a value?). Currently it clutters the legend with no purpose.

I wish I knew a bit more JavaScript so I could do this myself. Keep up the good work!
```

**Comment by timelyportfolio** [comment]
@markriseley I was able to take a first stab at implementation of your ideas.

1.  `legendOrder` argument.  Also, I added some logic to sort by descending value from the top level of the hierarchy if `legendOrder` not provided.
2.  `colors` argument.  You can do provide an array of hexadecimal colors to use such as `colors = blues9`.
3.  Implemented with `percent`, `count`, and `explanation` arguments.  To use explanation, you can do something like `sunburst(sequence_data,,explanation="function(d){return d.name}")`.
4.  `root` suppressed.  Can't imagine ever needing.

**Comment by markriseley** [comment]
Thanks, great to see it. Keep up the good work!

**Comment by timelyportfolio** [comment]
Feel free to reopen.  Thanks for all the great ideas.
