### ISSUE TITLE
HTML file exported with "Save as Web Page..." from RStudio Viewer is broken

### ISSUE THREAD

**Issue by kjedrzejewski** [timelyportfolio/sunburstR#20]
I've generated it in RStudio using code "Sunburst 1" from https://github.com/timelyportfolio/sunburstR/blob/master/inst/examples/example_flexdashboard.Rmd .

Exported HTML file for some reason contains an escaped fragment:

```
<pre><code>&lt;div&gt;
  &lt;div class=&quot;sunburst-main&quot;&gt;
    &lt;div class=&quot;sunburst-sequence&quot;&gt;&lt;/div&gt;
    &lt;div class=&quot;sunburst-chart&quot;&gt;
      &lt;div class=&quot;sunburst-explanation&quot; style=&quot;visibility:hidden;&quot;&gt;&lt;/div&gt;
    &lt;/div&gt;
  &lt;/div&gt;
  &lt;div class=&quot;sunburst-sidebar&quot;&gt;
    &lt;input type=&quot;checkbox&quot; class=&quot;sunburst-togglelegend&quot;&gt;Legend&lt;/input&gt;
    &lt;div class=&quot;sunburst-legend&quot; style=&quot;visibility:hidden;&quot;&gt;&lt;/div&gt;
  &lt;/div&gt;
&lt;/div&gt;</code></pre>
```

**Comment by timelyportfolio** [comment]
How did you export the HTML?

**Comment by kjedrzejewski** [comment]
I'm using Export -> Save as webpage in built-in RStudio viewer.
<img width="500" alt="zrzut ekranu 2016-09-14 o 10 40 24" src="https://cloud.githubusercontent.com/assets/8270726/18507299/b6a41c0a-7a67-11e6-8980-f9008b937b81.png">

**Comment by timelyportfolio** [comment]
Closing but feel free to reopen if not fixed with newer RStudio versions.
