### ISSUE TITLE
CRAN-bound

### ISSUE THREAD

**Issue by timelyportfolio** [timelyportfolio/sunburstR#22]
`sunburstR` will be CRAN-bound by the end of the week 2016-08-20.  I would love suggestions, improvements, examples to make it as good as possible before it is an official `R` package.

**Comment by voxnonecho** [comment]
Some suggestions:

Add more native options to play with legend / breadcrumb trail without having to rely on custom JS
- Toggle on/off visibility of legend / breadcrumtrail  (and the possibily to have legend showing by default - related to #15)
- Resize text (maybe a robust implementation of the idea in #7 with `tasks`, but generalized for both legend and / breadcrumtrail ?)

Add options for labels on slices

**Comment by timelyportfolio** [comment]
@voxnonecho all very nice suggestions.  I'm afraid of adding too much before CRAN concerned that a not fully tested set of functionality will then linger as an official release.  I'll add each item as a separate issue if no already out and tag for next release.  Thanks so much for all the help!

**Comment by timelyportfolio** [comment]
on cran now https://cran.r-project.org/web/packages/sunburstR/index.html

**Comment by msusol** [comment]
Is there a plan to upgrade to using d3.v4 ? The code currently uses 3.5.17 in d3r. I would like to help upgrade to 4.5 either here or in d3r

**Comment by timelyportfolio** [comment]
@msusol, I am eager to convert to `d3v4`, and the conversion is fairly straightforward (see [Kerry Rodden's d3v4 version](https://gist.github.com/kerryrodden/766f8f6d31f645c39f488a0befa1e3c8)).  However, I have not done yet because of other issues with `d3` in `global/window` (see https://github.com/christophergandrud/networkD3/issues/162) when combined with `d3v3` htmlwidgets.  Currently, I favor a standalone `sunburst.js`.  I will try to sketch out this approach in the next one or two weeks.

Thanks so much for using and offering to help!

**Comment by msusol** [comment]
what has been the uptake on using the package d3r? is this package just to facilitate htmlwidgets?

my need for this package is to generate the sunburst view in R, and knit to html for reports.

let me know how I can contribute in the short term.

**Comment by msusol** [comment]
@timelyportfolio, any progress on making this a stand alone sunburst R package in d3 v4? I have had to delete the d3 v3 package as they (my employer) deprecated d3 v3.

**Comment by timelyportfolio** [comment]
Thanks @msusol for the ping.  No plans yet.  I estimate the effort will require about 15-20 hours of work.  I recently left my full-time gig, so hours are sparse right now.  I do intend to complete within the next couple of weeks/months.

**Comment by timelyportfolio** [comment]
@msusol, the fantastic @cjyetman has offered to help with this, so see #36 to track progress.

**Comment by timelyportfolio** [comment]
Also, going to close this issue down.  Please reopen new issue, so that I can track.  Thanks everyone for a great thread.
