### ISSUE TITLE
Please make this package available on CRAN. 

### ISSUE THREAD

**Issue by sillasgonzaga** [timelyportfolio/sunburstR#23]
Github is blocked at my workstation (Yes, I know it's ridiculous) so I cannot download your package using devtools.  I know I can download it as a zip file and send it to my work email but it would be easier for me if I could just downloads from CRAN.

**Comment by timelyportfolio** [comment]
should be on its way by end of day.  We'll see how smooth it is :)

**Comment by timelyportfolio** [comment]
@sillasgonzaga on CRAN now, yay!

**Comment by sillasgonzaga** [comment]
Thanks!
