### ISSUE TITLE
Clarify documentation of colors parameter

### ISSUE THREAD

**Issue by wngrtn** [timelyportfolio/sunburstR#25]
I use csv data to create a sunburst diagram, but I cannot figure out how to assign colors to the individual elements. The documentation for `sunburst`'s color argument recommends that I either supply a 'vector of strings representing colors as hexadecimal for manual colors' or if I wanted 'precise control of colors, supply a list with range and/or domain'.

Can somebody provide more detail on how to add colors?

Specifically, if I supply a vector, how will the elements of the vector be used, and if I supply a list, what do I have to supply as `range` or `domain`?

**Comment by timelyportfolio** [comment]
Does this https://github.com/timelyportfolio/sunburstR/issues/17#issuecomment-225233554 help?  If not, I'll be happy to clarify.  You are correct in your statement that the documentation is insufficient, and I will work to resolve that.  Glad you are using `sunburstR`.

**Comment by timelyportfolio** [comment]
Going to close.  Please reopen if not solved or addressed.
