### ISSUE TITLE
shiny integration

### ISSUE THREAD

**Issue by keeganhines** [timelyportfolio/sunburstR#3]
Thanks for this great package @timelyportfolio  - Just wondering if you've attempted shiny integration here yet. You've included `sunburstOutput()` and `renderSunburst()`, and these work great right off the bat. But I've noticed a strange behavior -

If we try to produce a new result from `renderSunburst()` in response to any user input, the resulting plot seems to *append* the relevant data instead of *replacing* it. 

Here's a simple example to demo.

https://github.com/keeganhines/sunburstRshiny

 This is most noticeable as the label grows and grows as you interact with the slider. I'm kinda stumped, I can't imagine what aspect of `htmlwidgets` is appending the data. Do you have any guess?

**Comment by timelyportfolio** [comment]
@keeganhines As I mentioned  in the post, I broke some of my rules in putting this together, and the sloppiness is surfacing.  I think it is all fixed.  Let me know if it is not.

**Comment by timelyportfolio** [comment]
Using the little bit of `invalidateLater` trick learned from @jcheng5, here is an example.

```
library(shiny)
library(sunburstR)

sequences <- read.csv(
  system.file("examples/visit-sequences.csv",package="sunburstR")
  ,header=F
  ,stringsAsFactors = FALSE
)


server <- function(input,output,session){
  
  sequences <- read.csv(
    "./inst/examples/visit-sequences.csv"
    ,header=F
    ,stringsAsFactors = FALSE
  )
  
  output$sunburst <- renderSunburst({ 
    invalidateLater(1000, session)

    sequences <- sequences[sample(nrow(sequences),1000),]
    
    sunburst(sequences) 
  })
}


ui<-fluidPage(
  sidebarLayout(
    sidebarPanel(

    ),
    
    # plot sunburst
    mainPanel(
      sunburstOutput("sunburst")
    )
  )
)

shinyApp(ui = ui, server = server)
```

**Comment by keeganhines** [comment]
Great, thanks for these changes, the fixes for Shiny definitely work. 

In your Shiny example here, do you see the following js console errors (and a blank sunburst plot)?

    Error: Invalid negative value for <svg> attribute height="-70"
    Error: Invalid negative value for <circle> attribute r="-35"

**Comment by timelyportfolio** [comment]
I don't.  Will explore later.  For now, can you try providing a height and width for sunburstOutput?

**Comment by timelyportfolio** [comment]
What browser?

**Comment by timelyportfolio** [comment]
Also you might want to devtools::install_github one last time since I was firing away with changes.

**Comment by keeganhines** [comment]
Still seeing the same problem with the latest commit, setting `width` and `height` and with Chrome, Firefox, Safari. 

A little more on the stack trace for the error:

![image](https://cloud.githubusercontent.com/assets/6156395/9521585/b28a52b8-4c9d-11e5-8963-bae1c144d8c1.png)

**Comment by keeganhines** [comment]
So I can trace it all back to  line 20 of `sunburst.js` 

![image](https://cloud.githubusercontent.com/assets/6156395/9522058/7bff7f0e-4ca0-11e5-8356-a29d128ce1b2.png)

The console error is that the `height` is being set as `-70` and radius as `-35`, so this implies that `el.getBoundingClientRect().height` is returning `0`. 

This problem persists even when I specify the arguments as `sunburst(sequences, height=1000, width=1000)`.

**Comment by keeganhines** [comment]
So it seems that the element with id `#sunburst` was being given no dimension, so adding this to the `ui` fixes the problem

    tags$head(tags$style("#sunburst {width:500px;height:500px; position:relative;}")),

**Comment by timelyportfolio** [comment]
Oh, I know.  Try to devtools::install_github("ramnathv/htmlwidgets").  There was a pull https://github.com/ramnathv/htmlwidgets/pull/148 that I think will fix the problem.

**Comment by timelyportfolio** [comment]
@keeganhines, you can verify by doing this.

```
> sunburstOutput("sunburst")
<div class="sunburst html-widget html-widget-output" id="sunburst" style="width:100%; height:400px; position:relative;">
```

**Comment by keeganhines** [comment]
yea, that's exactly it, thanks!
