### ISSUE TITLE
Legend SurnBurstR

### ISSUE THREAD

**Issue by mimeides** [timelyportfolio/sunburstR#31]
Hi,
  I want to know if it possible to reduce the legend (manipulate the legend area) in Sunburst graph ? 

Tks a lot.

Mimeides

**Comment by aakbarie** [comment]
you control the legend sizing within the sunburst function:
`sunburst(yourDaya, legend = list(w = 200))`

**Comment by mimeides** [comment]
Hi, Thks a lot for your response 
  I did it but it seems to control the width but not the legend's FontSizing (sizing of the attributes)

Mimeides

**Comment by timelyportfolio** [comment]
Going to close since addressed in #35

**Comment by mimeides** [comment]
Excuse me for my late .  Thanks a lot for your reply !!!!!!  Great package !!!!!! 

    Le Mardi 30 janvier 2018 12h52, timelyportfolio <notifications@github.com> a écrit :
 

 Closed #31.—
