### ISSUE TITLE
does this library function on d3 vs 3.5.15 vs 3.5.17 ?

### ISSUE THREAD

**Issue by msusol** [timelyportfolio/sunburstR#32]
My company has an internal third_party library for R packages, and wants me to use existing d3.min.js in third_party that is only versioned to 3.5.15. Due to d3 v3 deprecation, they will not want me to update to 3.5.17 for offline use in d3r package that sunburstR relies on. 

Is there a critical issue if I were to use 3.5.15 instead of 3.5.17?

**Comment by timelyportfolio** [comment]
No, I do not think there will be any problem whatsoever using `3.5.15`.  At one point, I considered allowing any verson in `d3r`, but size becomes a problem especially with CRAN.  Let me know if you need any pointers on ways of accomplishing this.

**Comment by cjyetman** [comment]
this is probably irrelevant now that sunburstR has been [converted to D3v4](https://github.com/timelyportfolio/sunburstR/issues/36)?
