### ISSUE TITLE
Font size of legend

### ISSUE THREAD

**Issue by tyjselina** [timelyportfolio/sunburstR#35]
@timelyportfolio  I am trying to figure out how to change the font size of the legend, would you please give an example of changing the font size of legend? Also, do you have any idea of changing the size of sunburst chart itself(not the legend)?

Thank you for your great job!

Selina

**Comment by timelyportfolio** [comment]
Sorry for the slow response.  I will try to post some examples this week if not too late.

**Comment by nbartonicek** [comment]
Hello! Has this been resolved?

**Comment by cjyetman** [comment]
As far as I know, this is not / has not been built-in yet, but you can achieve this by using `htmlwidgets::onRender` to add a little JavaScript to set the legend's `font-size` attribute...
```r
library(sunburstR)
library(htmlwidgets)

sequence_json <- jsonlite::fromJSON(
    system.file("examples/visit-sequences.json",package="sunburstR"),
    simplifyDataFrame = FALSE
)
sun <- sunburst(sequence_json, withD3 = T)

htmlwidgets::onRender(
    sun,
    "
    function(el, x) {
    d3.selectAll('.sunburst-legend text').attr('font-size', '24px');
    }
    "
)
```

**Comment by timelyportfolio** [comment]
Thanks so much @cjyetman!

**Comment by StanSilas** [comment]
Thank you for the amazing package!  and the quick hack for font size.

I have about 30 labels in the legend. Is it possible to display them in two columns?
At the moment the bottom ones just disappear. 

 @cjyetman @timelyportfolio

**Comment by timelyportfolio** [comment]
I believe this has been solved.  Please feel free to reopen.
