### ISSUE TITLE
convert to d3v4

### ISSUE THREAD

**Issue by timelyportfolio** [timelyportfolio/sunburstR#36]
This is part of a grand refactor.  I plan to use Github Projects to track and manage the conversion, so see https://github.com/timelyportfolio/sunburstR/projects/1 to monitor, cheer, or help.

**Comment by timelyportfolio** [comment]
Will track with `d3v4` branch https://github.com/timelyportfolio/sunburstR/tree/d3v4 so please direct any pulls there.

**Comment by cjyetman** [comment]
I have a functioning version of `sunburstR` converted to D3v4 here: https://github.com/cjyetman/sunburstR/tree/d3v4

It can be installed and tested with:
```r
devtools::install_github('cjyetman/sunburstR', ref = 'd3v4')
```

It would be great if a few people could test it out and give some feedback.

I'll make a PR as soon as @timelyportfolio gives the thumbs up.

**Comment by timelyportfolio** [comment]
pr away !! Thanks!

**Comment by timelyportfolio** [comment]
Thanks!!!!!!  All I found were some examples that still used `d3v3` api in the appended JS.  After a little more testing and maybe some feedback (very hard to get), I will close this and move on to the other items in the project https://github.com/timelyportfolio/sunburstR/projects/1.  Thanks.

**Comment by timelyportfolio** [comment]
One note I made a mess of the git history.  I haven't squashed in a while and messed it up.  Shouldn't affect anything, but does look odd.

**Comment by cjyetman** [comment]
pinging @msusol here because he was eager for a D3v4 version in #22... you can install the dev version with this and give feedback...
```r
devtools::install_github('timelyportfolio/sunburstR', ref = 'd3v4')
```

**Comment by msusol** [comment]
Something seems odd about the display of the slices selected?

![sunburstr_d3v4_test1](https://user-images.githubusercontent.com/2815031/27006293-7a6fcb08-4ded-11e7-90af-112086b65060.jpg)

**Comment by timelyportfolio** [comment]
@msusol that is strange.  Which sequences.csv are you using?  `sunburstR` still requires lots of testing, so I would love to figure this out.

**Comment by msusol** [comment]
[sunburst.csv.zip](https://github.com/timelyportfolio/sunburstR/files/1066119/sunburst.csv.zip)

**Comment by cjyetman** [comment]
I think the levels have to be separated by a '-', no? Which is unfortunate in your case because you have some negative numbers in your path names.

**Comment by msusol** [comment]
forgot how that file was created, but there are no negative numbers, replacing ">" with "-" fixed that issue.

Now what's missing, i the total number of sequences that take this path. so for 16.8% for 4360 > 22 sequence, would like to see under the path chosen visual, the 100% and total number of sequences under 4360, then under "22" 16.8% of the total.

**Comment by timelyportfolio** [comment]
The JavaScripy hierarchy can fail quite easily.  When I get some time I will try to see if this is a hierarchy construction issue or a vis layout issue.  Thanks for sharing the file.

**Comment by msusol** [comment]
here is updated csv
[sunburst.csv2.zip](https://github.com/timelyportfolio/sunburstR/files/1066146/sunburst.csv2.zip)

**Comment by cjyetman** [comment]
@msusol I'm not sure I understand what you're asking? Is this something not working the way it should (a bug), or is this a new feature you would like to see added? If it's a new feature you'd like to see added, it would be better if you opened a new issue for that.

Have you tried the `count = TRUE` argument? It adds the count and total in the explanation in the middle of the sunburst.
```r
sunburst(sequences, count = T)
```

**Comment by timelyportfolio** [comment]
Ok, finally got a chance to look at this and read more carefully.  @msusol, it seems like you would like to know how to pursue more advanced customization of the ultimate visual.  Is this correct?  Are you talking about something like this [example](http://www.d2bjs.org/example_categories/5/entries/19) from `d2b`?

![image](https://user-images.githubusercontent.com/837910/27010426-aee606aa-4e69-11e7-9d63-642793b2ea8b.png)

If so, a result like the `d2b` example is currently out of the scope for the existing `sunburst` function.  However, I had already mentioned to @cjyetman that I am considering adding another widget for creating a `d2b sunburst` within `sunburstR`.  I will need some time to properly integrate though, and I think completing the conversion is higher priority and also a prerequisite before pursuing this.

If this is the case, I feel like the best thing to do is open another issue to track progress toward this goal.  Would love to hear your thoughts?

**Comment by timelyportfolio** [comment]
@cjyetman, seems this is complete, so moving on to #37 and #40.  Thanks!!!!!
