### ISSUE TITLE
standalone d3v4 build

### ISSUE THREAD

**Issue by timelyportfolio** [timelyportfolio/sunburstR#40]
Build the JS dependency as a standalone file, so we do not face d3v3 vs. d3v4 type issues again.  See [d3horizonR](https://github.com/timelyportfolio/d3horizonR) and the forked [`d3sankey`](https://github.com/timelyportfolio/sankeyD3/tree/standalone) as examples.  This should be fairly straightforward.

**Comment by msusol** [comment]
let me know how I might be able to help

**Comment by timelyportfolio** [comment]
any superpowers 🥇 ? :)

**Comment by timelyportfolio** [comment]
believe this is done, but will evolve with #37
