### ISSUE TITLE
BREAK API - change data argument

### ISSUE THREAD

**Issue by timelyportfolio** [timelyportfolio/sunburstR#43]
It has bothered me for quite a while that `sunburst()` takes two arguments to pass `data`.  I would much prefer the [approach in `d3treeR`](https://github.com/timelyportfolio/d3treeR/blob/master/R/d3tree.R#L71-L105) that takes one `data` argument and attempts to resolve based on `class`.  I have not changed for fear of breaking the API, but since we are taking major step in version, I think I will make the adjustment.  Any feedback??

**Comment by jonmcalder** [comment]
FWIW, I agree with this change. Another benefit of having a single data argument is that it makes the `sunburst()` function pipe (%>%) friendly which it currently isn't if you're feeding it JSON data.

**Comment by timelyportfolio** [comment]
Thanks @jonmcalder and good point on the pipe-ability.  I guess I could leave the `jsondata` and `csvdata` arguments around in this version with a deprecation warning, so that it is not as jarring a change.

**Comment by timelyportfolio** [comment]
Going to close, since this seems done. Please reopen if there are any issues.
