### ISSUE TITLE
Rounding in count parameter

### ISSUE THREAD

**Issue by vrybkin** [timelyportfolio/sunburstR#49]
Hi Kent,

To begin, thank you for this incredibly helpful and easy to use package. I noticed that it seems like there is rounding that occurs in the count/explanation portion of the figure. This rounding seems to be scaled logarithmically. Might you know of any work around, like perhaps a custom "explanation" parameter like `explanation = "function(d){return d.data.name}"`, to remove this rounding convention? I understand that the sunburst plot is meant to give ballpark market share/sequence numbers and is not meant for any "rigorous" analyses where that level of precision should matter, but it would still be nice to see more exact counts. For example, I'd like to see a count of 105 instead of 110.

Thank you so much for your time!

**Comment by cjyetman** [comment]
try something like this...
```r
data <- read.csv(header = T, text = "
paths, counts
\"City: Chicago\", 132
\"City: New York\", 205
\"City: Los Angeles\", 124
\"City: Houston\", 105
")
library(sunburstR)
sunburst(data, explanation = "function(d) { return d.value + ' of ' + this }")
```

**Comment by timelyportfolio** [comment]
thanks @cjyetman!

**Comment by vrybkin** [comment]
Thank you for the prompt responses, @cjyetman  and @timelyportfolio! I used your suggestions to come to this implementation: `explanation = "function(d) { return ( Math.round((d.value / this *  100) * 100) / 100 ) + '%<br>' + d.value + ' of ' + this }"` and it works great!

Thanks again!

**Comment by timelyportfolio** [comment]
closing for now...please reopen if you need anything else.  @vrybkin, thanks for using and asking.  Love to see examples and uses.  Also love feedback, so please share any or all.
