### ISSUE TITLE
Shiny implementation: Plot is not rendering correctly

### ISSUE THREAD

**Issue by icarvalhosa** [timelyportfolio/sunburstR#5]
Thanks for the widget, really like it. 

I am trying to use it in a shiny App. However, the plot doesn't seem to render correctly. 
I tried to use the example in the package. It is showing fine in the RStudio Viewer. However, when I run the shinyApp, the plot is not showing. It shows the legend, but the legend keeps flashing and changing.
 
Any ideas or suggestion that I can get it working would be greatly appreciated. 

Thanks a lot and keep up with the good work. :)

**Comment by timelyportfolio** [comment]
Thanks for using.  Can you copy/paste `sessionInfo()` or `devtools::session_info()` to help me debug?

**Comment by icarvalhosa** [comment]
It started working fine again after I re-installed my shiny and sunburstR. Sorry about the false alarm.
Thank you for your great work tho. :)
