### ISSUE TITLE
Is it possible to size wedges by area instead of length?

### ISSUE THREAD

**Issue by harijay** [timelyportfolio/sunburstR#50]
Sorry to ask this question as an "issue". I couldnt find a mailing list so posting this here.

Is it possible to have sunburst represent the size by area instead of by length.

I am aware of the pluses of "length" visually rather than area perception..but I was wondering if there is a way for sunburst to switch to a mode where it sizes the wedges by area.

**Comment by timelyportfolio** [comment]
I believe I understand the question, but I am not sure how to accomplish this.  I remember this discussion from a while back https://groups.google.com/forum/#!topic/d3-js/mcJ8GE6_fq4 but don't think it really applies.  If you have any links, I would enjoy seeing them.

**Comment by timelyportfolio** [comment]
going to close due to lack of response.  Please feel free to reopen.
