### ISSUE TITLE
Problem to show in new window

### ISSUE THREAD

**Issue by mashranga** [timelyportfolio/sunburstR#51]
Does not work with windows() or x11() commend . 
Can you please check the problem ?

**Comment by cjyetman** [comment]
I assume you're using RStudio? `sunburstR` creates an `htmlwidget`, which by default in RStudio displays in the viewer pane. You can turn off that default, causing the `htmlwidget` to display in your default web browser instead by doing this...
```r
library(htmlwidgets)
library(sunburstR)

sequences <- read.csv(
  system.file("examples/visit-sequences.csv",package="sunburstR")
  ,header = FALSE
  ,stringsAsFactors = FALSE
)[1:100,]

sunburst(sequences, sizingPolicy = htmlwidgets::sizingPolicy(viewer.suppress = TRUE))
```

**Comment by timelyportfolio** [comment]
@cjyetman, very nice of you to jump in and answer.  Thanks!  Doesn't sound like @mashranga is in RStudio, but if so `options(viewer = NULL)` will default to the browser.

@mashrange, perhaps we should explain a little more.  While `windows()` and `x11()` create graphic devices for rendering static content (usually `png`) from `graphics`, `lattice`, `ggplot2`, htmlwidgets produce HTML/CSS/JS that requires a browser (RStudio Viewer, Chrome, Firefox, etc.) to render.

**Comment by cjyetman** [comment]
When running my example code (for example) in the standard R GUI, it always opens in a new window (browser window)... that's why I assumed RStudio. :-)
