### ISSUE TITLE
Exclusive breadcrumb

### ISSUE THREAD

**Issue by Ammar-K** [timelyportfolio/sunburstR#54]
First of all, thank you for the great widget, it's my favorite HTML widget in R. 

I've been trying to generate flexdashboard that contains two sunbursts. 
a weird behavior occurs when one of the sunburst didn't show the sequence breadcrumb, after investigating, it seems like the breadcrumb is Exclusive for one sunburst (first sunburst to hover over).

**Comment by timelyportfolio** [comment]
Thanks for the report, and that is troubling.  In all my htmlwidgets, I tried to insure that they would play well with multiple on a page.  I wonder if this sneaked in with the upgrade to d3v4.  I will try to recreate and debug.

**Comment by timelyportfolio** [comment]
@Ammar-K, I checked quickly, and breadcrumbs with multiple sunbursts on a page seems to work.  See  the last part of [example](https://github.com/timelyportfolio/sunburstR/blob/master/inst/examples/example_ngram.R).  If you have a repoducible example, please share, and I'll be happy to debug.  Thanks!!

**Comment by timelyportfolio** [comment]
Glad you got it sorted out.  I will close, but feel free to repopen if you experience any trouble.

**Comment by Ammar-K** [comment]
The issue will occur using flexdashboard with IE browser. 
This working fine with chrome.

**Comment by timelyportfolio** [comment]
Thanks for the update.
