### ISSUE TITLE
Incorrect numbers due to rounding

### ISSUE THREAD

**Issue by Cat1796** [timelyportfolio/sunburstR#57]
Hi,

I have found a problem in the way the (displayed) numbers are computed. It seems the problem comes from the rounding. Example, if my actual numbers on the edge of the chart are 0.775%, they get rounded to 0.78%. Let's assume I have 4 such slices for a correct total of 3%. The circle a level above will have a slice displaying not 3% but 3.12%, that is, 4*0.78%(rounded). In effect, the use of rounded number compounds imprecisions as one goes further up the chart.
![snap4](https://user-images.githubusercontent.com/13978249/35431510-07b3554a-027d-11e8-82ef-8649c24290bd.png)
![snap7](https://user-images.githubusercontent.com/13978249/35431511-07d70c4c-027d-11e8-8a65-fa21b29856e2.png)
![snap8](https://user-images.githubusercontent.com/13978249/35431512-07f4f1c6-027d-11e8-86ff-2e575821c740.png)

**Comment by timelyportfolio** [comment]
@Cat1796, thanks for filing the issue.  I will dig into the root of this problem and report back.  Can you fix by multiplying the exposure by 1000?  Also, if you have the time, willingness, and understanding, does the same problem occur if you create the hierarchy using `d3r` to supply a `json` version of the data?

**Comment by Cat1796** [comment]
Multiplying by 1000 seems to do the trick.

I didn't go through d3_nest. If it helps though, it seems that version 0.6.5 isn't affected by this issue, as it appeared only when I updated your package.

**Comment by timelyportfolio** [comment]
Going to close.  Please reopen if still an issue.  Thanks for posting @Cat1796.
