### ISSUE TITLE
Add text on sunburst segments

### ISSUE THREAD

**Issue by fbreitwieser** [timelyportfolio/sunburstR#66]
Thanks a lot for the recent advancements with `d2b`! Looks great, love the zoom functionality.

I'd like to add text to the circle segments, something similar to http://marbl.github.io/Krona/examples/phymmbl.krona.html?collapse=false&color=true&key=false . Not sure if it would be easy to accomplish unless the sunburst is pretty big, though

**Comment by fbreitwieser** [comment]
I also found an implementation by Mike Bostock to show text radially on the sunburst:
http://bl.ocks.org/mbostock/910126

**Comment by timelyportfolio** [comment]
pairs nicely with #59.  I would like to add labels, but won't be able to address until a couple of weeks from now.

**Comment by fbreitwieser** [comment]
Thanks, yep that's exactly that. I'll close this issue as duplicate
