### ISSUE TITLE
Labels on Reveal.js

### ISSUE THREAD

**Issue by mmc00** [timelyportfolio/sunburstR#69]
Hi, I have a problem when I used sund2b in Reveal.js, once they appear on the slide the label does not show properly.

<img width="675" alt="img" src="https://user-images.githubusercontent.com/32829068/40565804-31ce6020-602b-11e8-89fc-d7d7fa9ef86b.png">

**Comment by mmc00** [comment]
I fixed with a custom css file with the following code: 
.d2b-tooltip {
    z-index: 1;
}

**Comment by timelyportfolio** [comment]
@mmc00 so glad you figured it out and really appreciate you reporting back.  Hope you are enjoying the package.
