### ISSUE TITLE
d2b add showlabels and click event

### ISSUE THREAD

**Issue by dockstreet** [timelyportfolio/sunburstR#71]
Hi,

Could the sunburstChartConfig be a parameter to allow for showLabels and a click event to observe as the non-d2b sunburstR?

**Comment by timelyportfolio** [comment]
@dockstreet, are these options with `d2b`?  Sorry if I am misunderstanding.

**Comment by dockstreet** [comment]
@timelyportfolio  I saw an example here 
https://github.com/d2bjs/d2b/issues/13
and in this fiddle:
https://jsfiddle.net/3cyeddyp/4/

does this help explain a bit of what I'm trying to achieve by showing the labels

+ is there a way to add an observable click event and mouse over as the non-d2b sunburst?

**Comment by jtrecenti** [comment]
+1 to click event and mouse over as the non-d2b sunburst

**Comment by timelyportfolio** [comment]
Sorry, I should have added this in the last version.  I forgot.  Added `showLabels` argument to `sund2b` and just submitted to CRAN.  Thanks for the issue.

**Comment by timelyportfolio** [comment]
In terms of click event, if for shiny this was added a couple versions ago.  See https://github.com/timelyportfolio/sunburstR/blob/master/inst/examples/example_shiny.R and https://github.com/timelyportfolio/sunburstR/blob/master/R/shiny.R.

**Comment by timelyportfolio** [comment]
Going to close for now, but please reopen if you would like to see better event integration.
