### ISSUE TITLE
Double counting in sund2b

### ISSUE THREAD

**Issue by monicarajamanohar** [timelyportfolio/sunburstR#78]
Hi,
I was trying to execute the following and I found that sund2b double counts the pre-summed tree. In sunburst, there is an option sumNode = FALSE to avoid double counting of presummed trees.
How can I do the same with sund2b?
Thanks
Monica

library(treemap)
library(d3r)
rhd <- random.hierarchical.data()
tm <- treemap(
  rhd,
  index = paste0("index", 1:3),
  vSize = "x",
  draw = FALSE
)$tm
sund2b(
  d3_nest(tm, value_cols = colnames(tm)[-(1:3)]),
  colors = htmlwidgets::JS(
    # yes this is a little different, so please pay attention
    #  "function(d) {return d.color}" will not work
    "function(name, d){return d.color || '#ccc';}"
  ),
  valueField = "vSize"
)

**Comment by timelyportfolio** [comment]
Hi @monicarajamanohar I think this was fixed in `d2b` https://github.com/d2bjs/d2b/commit/134079a7917a9083909fb8853453fa5f78e4e09a.  I will plan to update `d2b` tonight.

**Comment by timelyportfolio** [comment]
@monicarajamanohar I updated `d2b`, and I believe it is fixed.  Using the example from #62, 

```
library(sunburstR)
library(d3r)

df <- data.frame(
  index1 = c(rep("A",3),"B"),
  index2 = c(NA,"A.1","A.1",NA),
  index3 = c(NA, NA, "A.1.1", NA),
  size = c(5,5,5, 10),
  stringsAsFactors = FALSE
)

sunburst(
  d3_nest(df, value_cols="size"),
  count = TRUE
)

sund2b(d3_nest(df, value_cols="size"))
```

![image](https://user-images.githubusercontent.com/837910/45395855-ba321d80-b5fd-11e8-8841-463183e53b91.png)


I will try to prepare a CRAN release by the end of the weekend.

**Comment by monicarajamanohar** [comment]
Any luck updating the CRAN?

**Comment by timelyportfolio** [comment]
@monicarajamanohar  just submitted so we'll see if it gets approved

**Comment by timelyportfolio** [comment]
@monicarajamanohar this was accepted last night on CRAN.  Please let me know once you get a chance to test.

**Comment by monicarajamanohar** [comment]
I checked and it works beautifully!!! Thank you for giving such a quick resolution :D. I will close the issue now.
