### ISSUE TITLE
Reducing run-time of Sunburst

### ISSUE THREAD

**Issue by prab0509** [timelyportfolio/sunburstR#84]
First of all, thankyou for building such an amazing feature in R. I am using SunburstR and have a small query regarding which your input could be very useful. I have a hierarchial dataframe having 46k records. The time  taken for sunburst to render the chart is more that 10 mins. Is there a way to optimize this process. Thanks.

**Comment by timelyportfolio** [comment]
Considering https://github.com/timelyportfolio/d3r/issues/18 but in general even after conversion we would expect very poor performance from an `svg` with 46k nodes.
