### ISSUE TITLE
Any way to sort by name/category?

### ISSUE THREAD

**Issue by D0g4** [timelyportfolio/sunburstR#85]
First of all, manny thanks for this very neat package.
Now, I was wondering if I could re-order my chart according to categories.
I will explain:
For one of the levels of the chart, I have the following categories: "0 to 3h"; "3 to 7h"; and "7 to 12h".
So, it'd be optimal to have in that order, instead of by the size of them (most of the times I have more samples "3 to 7h" than "0 to 3h").
No, if there is no way to do it automatically, would it be possible to do it at least manually?

I hope to have this issue heard, 'cause I really like this one.
Thank you very much and go one again.

**Comment by timelyportfolio** [comment]
@D0g4 thanks for filing the issue.  Perhaps [this example](https://github.com/timelyportfolio/sunburstR/blob/master/inst/examples/example_calendar.R) will help illustrate how to sort.  Please let me know if you have any more questions.

**Comment by timelyportfolio** [comment]
Closing but please reopen if the above answer did not solve.
