### ISSUE TITLE
Legend names being cutoff in the output.

### ISSUE THREAD

**Issue by jrangeles** [timelyportfolio/sunburstR#9]
I'm wondering if the breadcrumb feature for the path sequences, could also be applied for the legends or is there another way so that the names in the legend doesn't cutoff? 

Also is there a way to show the legends by default?

**Comment by timelyportfolio** [comment]
Both good ideas... Maybe I can look by end of week.  Here is a [post](http://www.buildingwidgets.com/blog/2016/2/12/time-isnt-money) describing my current situation.

**Comment by jrangeles** [comment]
I've reverse engineered how you did the breadcrumb codes and was able to do the same thing for the legends. You could take a look at it from my branch of your repo and I could push it if you like.

On a side note, I truly appreciate the effort you've put into this. I'll try to figure out how to improve it on my own since I'm broke. I got some ideas in mind. Got to study up on D3.js though. It would be great if you could lend a hand.

**Comment by timelyportfolio** [comment]
Glad you figured it out.  I'm not saying I won't do any more volunteer open source.  Just that folks should not expect same-day or even same-week response times.  I like your solution.  I'll see if anybody else requests this functionality, and if so, I will use/extend your approach.  Thanks so much for sharing your repo so others can see your work.  This will help complete the virtuous cycle.

**Comment by timelyportfolio** [comment]
@jrangeles I needed to make another change so I went ahead and applied `legend` for legend sizing.  Thanks for the motivation.  Please let me know if it does not work as you would expect.
