### ISSUE TITLE
Example doesn't work

### ISSUE THREAD

**Issue by Rezar** [timelyportfolio/sunburstR#91]
Hi your example in here:
https://cran.r-project.org/web/packages/sunburstR/vignettes/sunburst-2-0-0.html
has problem with tree object and it doesn't create the Subburst

**Comment by timelyportfolio** [comment]
@rezar thanks for filing the issue, but in the future more details would be helpful.  In this case, my guess is the `tidyr` update is the source of the trouble.  Please install the latest `0.8.7` version of `d3r` and let me know if this fixes the problem.

If not, please send session info and the error message.

**Comment by Rezar** [comment]
I am sorry for being too short. 
I have downloaded them all very recently. The tree creation in your example yields a different result and it seems wrong to me:
{"children":[{"name":"Useful","children":[{"name":"Animals and Nature","time":2,"colname":"prg"},{"name":"Documentaries","time":3.2,"colname":"prg"},{"name":"Indie Movies","time":2.9,"colname":"prg"},{"name":"Techn news","time":2,"colname":"prg"}],"colname":"qual"},{"name":"Waste","children":[{"name":"Reality shows","time":7.8,"colname":"prg"},{"name":"Political News","time":1,"colname":"prg"},{"name":"Blockbuster Movies","time":4.5,"colname":"prg"},{"name":"Ads","time":5.1,"colname":"prg"},{"name":"Celebrity News","time":1,"colname":"prg"}],"colname":"qual"}],"name":"root"}

**Comment by Rezar** [comment]
I am sorry for being too short.
I have downloaded them all very recently. The tree creation in your example yields a different result and it seems wrong to me:
{"children":[{"name":"a","children":[{"name":"a1","children":[{"name":10,"colname":"size"}],"colname":"level2"},{"name":"a2","children":[{"name":5,"colname":"size"}],"colname":"level2"},{"name":"a3","children":[{"name":2,"colname":"size"}],"colname":"level2"}],"colname":"level1"},{"name":"b","children":[{"name":"b1","children":[{"name":3,"colname":"size"}],"colname":"level2"},{"name":"b2","children":[{"name":8,"colname":"size"}],"colname":"level2"},{"name":"b3","children":[{"name":6,"colname":"size"}],"colname":"level2"}],"colname":"level1"}],"name":"root"}

**Comment by timelyportfolio** [comment]
@rezar I am sorry, but I am still confused.  What looks wrong about the result?  If you would like to inspect then `listviewer::jsonedit(tree)` gives us a good view of the transformed data.

![image](https://user-images.githubusercontent.com/837910/64475839-73fa9600-d14d-11e9-851f-4461ae6338e5.png)

I'd like to help.  Please follow the guidelines in [reproducible example](http://adv-r.had.co.nz/Reproducibility.html) so that I can better understand your issue.

**Comment by timelyportfolio** [comment]
Going to close.  Please reopen with additional details so that I can fix.
