### ISSUE TITLE
Sund2b tooltip customization

### ISSUE THREAD

**Issue by thulasirangan** [timelyportfolio/sunburstR#92]
Hi,
First of all many thanks for this package. I am currently using sund2b and I have a requirement to customize the tooltip.
Is there a way to show a different value in the tooltip and use something else for my size?
I see many properties listed here: http://docs.d2bjs.org/chartsAdvanced/sunburst.html. 
Is it possible to incorporate them in sund2b?

Thanks.

**Comment by timelyportfolio** [comment]
@thulasirangan thanks for filing the issue.  I have added the ability to customize the tooltip for `sund2b` and upgraded to the most current `d2b` release.  Please install `devtools::install_github("timelyportfolio/sunburstR")` if possible and see `?sunburstR::sund2bTooltip`.  I'll try to submit to CRAN soon.

**Comment by timelyportfolio** [comment]
@thulasirangan just a note I went ahead and submitted to CRAN if easier for you to install from there.  Please let me know if I can help achieve your desired tooltip.

**Comment by thulasirangan** [comment]
Hi,
Thanks for adding this enhancement. Now I am able to show customized content in the tooltip. 
But I see that the breadcrumb and the tooltip aren't in sync. Is it possible to add the same feature in the breadcrumbs? I am ok if you can provide a toggle to disable the breadcrumb as well.

Let me know if I can be of some assistance in integrating the breadcrumb customisation properties in the package.

Thanks.

**Comment by timelyportfolio** [comment]
@thulasirangan I added breadcrumb customization.  If possible please try with `devtools::install_github("timelyportfolio/sunburstR")`.

**Comment by thulasirangan** [comment]
Awesome.. Tried it out and it serves my purpose.. Many thanks.
