### ISSUE TITLE
No tidyselect variables were registered

### ISSUE THREAD

**Issue by andirey** [timelyportfolio/sunburstR#94]
I used "sunburstR" package.
But now it starts generate error
==
rlang::last_error()
<error>
message: No tidyselect variables were registered
class:   `rlang_error`
backtrace:
   1. shiny::runApp()
   8. shiny:::serviceApp()
   9. shiny:::flushReact()
  10. .getReactiveEnvironment()$flush()
  11. ctx$executeFlushCallbacks()
  12. base::lapply(...)
  13. shiny:::FUN(X[[i]], ...)
  14. shiny:::flushCallback()
  33. shiny:::run()
  34. ctx$run(.func)
  41. env$runWith(self, func)
  42. shiny:::contextFunc()
  43. shiny:::`<observer:output$plot_races_sunburst>`(...)
  78. shiny:::func()
  79. shiny:::orig(name = name, shinysession = self)
  81. shiny:::`output$plot_races_sunburst`(...)
  82. shiny:::origRenderFunc(...)
  95. func()
  96. sunburstR::sunburst(df, count = TRUE, legend = FALSE) app.R:562:4
  97. sunburstR:::csv_to_hier(data)
  98. d3r::d3_nest(df, value_cols = "size")
 108. dplyr::one_of(c(nonnest_cols[length(nonnest_cols)], value_cols))
 110. tidyselect::peek_vars()
 111. vars_env$selected %||% abort("No tidyselect variables were registered")
Call `rlang::last_trace()` to see the full backtrace
==
version of sunburstR is 2.1.2

How to fix it?

**Comment by timelyportfolio** [comment]
@andirey not sure but my first guess to fix would be to install the newest `d3r` with `install.packages("d3r")`.  Please let me know if this fixes.

**Comment by andirey** [comment]
Yes. After "d3r" it works. Thanks
Why do we need d3r btw?

**Comment by timelyportfolio** [comment]
@andirey `d3r` does the conversion into expected `d3` network format https://github.com/timelyportfolio/sunburstR/blob/master/R/converters.R.

**Comment by andirey** [comment]
OK. Thanks for the advice!
I hope it can be useful for someone else as well.

**Comment by timelyportfolio** [comment]
@andirey thanks for filing the issue.  The newest `tidyr` required modifications because of api change.  I modified `d3r` to accept both old and new api format.  Also, I have found the `data.frame` based network format as illustrated in  https://bl.ocks.org/timelyportfolio/e135afab3838dffd82226655245d3feb to be more workable than the original delimited structure.

**Comment by timelyportfolio** [comment]
Going to close.  Feel free to reopen.
