### ISSUE TITLE
Sunburst Plot Hangs

### ISSUE THREAD

**Issue by andrew-findlay** [timelyportfolio/sunburstR#95]
I'm finding that with a dataframe of anything more than 2/300 rows then the plot command simply hangs indefinitely. Is this a known issue or something unique to my R install?  I'm running OSX Catalina and experience it in R Studio and running through the terminal.

**Comment by timelyportfolio** [comment]
@andrew-findlay Sorry to hear.  How are you supplying data - csv/data.frame or list/d3r?

**Comment by timelyportfolio** [comment]
Closing ... please feel free to reopen.  Happy to try to resolve.  Looking into converting `d3r` to [`tidyfast`](https://github.com/TysonStanley/tidyfast) which might speed things up a bit.
