### ISSUE TITLE
Option to rename "root" in sund2b

### ISSUE THREAD

**Issue by cammyoung** [timelyportfolio/sunburstR#96]
Hi,

When displaying the `sund2b` plots in shiny, I always get the question "What does root mean?". Is there a simple way to rename it? I end up having to create a layer in the hierarchy that totals 100% and has the name I want for clarity, but it is still confusing to users of the dashboard.

Thanks for developing this! It's very straightforward to use, and looks great.

**Comment by timelyportfolio** [comment]
@cammyoung I am happy to hear that you are enjoying `sund2b`.  Very good question, and something that is now possible with version `2.1.2`.  Unfortunately the solution is not straightforward.  How are you supplying data to `sund2b`?  Are you using the csv method or passing a hierarchy from `d3r`?

**Comment by timelyportfolio** [comment]
@cammyoung I just added a `rootLabel` argument for `sund2b`.  If possible, will you install from Github with `install.github("timelyportfolio/sunburstR")` and let me know if this solves the issue?  Thanks.

**Comment by timelyportfolio** [comment]
@cammyoung I went ahead and pushed the change to CRAN so you can install.packages.  I am going to close but please reopen if this does not fulfill your objective.  Thanks!

**Comment by cammyoung** [comment]
Thanks so much for the quick response! This was exactly what I needed.
