### ISSUE TITLE
Modify sund2b breadcrumb size

### ISSUE THREAD

**Issue by alopgar** [timelyportfolio/sunburstR#98]
I did a sund2b plot using this code:

`ggsunb_st <- sunburstR::sund2b(sunb[,c("Taxonomy", "Standard")], width = "100%", height = 500)
`

The problem with output is the size of the breadcrumb, as it appears incomplete. I would like to change the size of the breadcrumb windows to fit my figure height.

![image](https://user-images.githubusercontent.com/43778995/78667081-9ff31b00-78d8-11ea-8b74-3d6e617c54af.png)

Is there an easy way to do this? 
Thanks!

**Comment by timelyportfolio** [comment]
Hi @alopgar thanks for the issue.  Have you tried adjusting CSS as discussed in https://github.com/timelyportfolio/sunburstR/issues/90?  Let me know if none of this makes sense and I'll be happy to help.

**Comment by timelyportfolio** [comment]
Closing since no response.  Please reopen if this is not solved.
